### ISSUE TITLE
培训机构又开了一家公司：深圳市思无涯科技有限公司

### ISSUE THREAD

**Issue by yunxag** [npcola/TI#47]
公司：深圳市思无涯科技有限公司
地址：深圳市宝安区新安街道安乐社区44区顺丰路15号金宝商务大厦8308

**Comment by yunxag** [comment]
> 公司：深圳市思无涯科技有限公司
> 地址：深圳市宝安区新安街道安乐社区44区顺丰路15号金宝商务大厦8308
公司：深圳市冠思科技有限公司
地址：深圳市宝安区新安街道安乐社区44区顺丰路15号金宝商务大厦8308

**Comment by ZGWS88** [comment]
已更新，感谢提供
